# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 2000

[line_break]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[cmake]
disabled = true

[golang]
disabled = true

[git_status]
stashed = ""

[git_commit]
tag_symbol = " "

[cmd_duration]
format = ""

[lua]
format = ""

# Workaround for WSL + systemd: https://github.com/starship/starship/issues/4555
[container]
disabled = true
