# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[python]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[git_status]
stashed = ""

[cmd_duration]
prefix = ""
